apiVersion: v1
kind: Secret
metadata:
  name: rds-secret
  namespace: fluid-ai
type: Opaque
stringData:
  DB_HOST: "ADD_RDS_ENDPOINT_LATER"
  DB_NAME: "fluiddb"
  DB_USER: "postgres"
  DB_PASSWORD: "ADD_PASSWORD_LATER"
  DB_PORT: "5432"