apiVersion: v1
kind: Secret
metadata:
  name: rds-secret
  namespace: fluid-ai
type: Opaque
stringData:
  DB_HOST: "fluid-ai-db.crakgmusgrst.ap-south-1.rds.amazonaws.com"
  DB_NAME: "fluiddb"
  DB_USER: "postgres"
  DB_PASSWORD: "bhakti123"
  DB_PORT: "5432"